#######################################################################
# tinyMBSE - CONFIGURATION                                             #
#######################################################################

# ---------------------------------------------------------------------
# General config
# ---------------------------------------------------------------------
general:
  pathtmp: /tmp
  pathplantuml: 

# ---------------------------------------------------------------------
# mySQL config
# ---------------------------------------------------------------------
db:
  host: localhost
  user: aajm
  pwd: gmv2gmv

# ---------------------------------------------------------------------
# PlantUML config
# ---------------------------------------------------------------------
plantUML:
 path: C:\Users\aajm\Desktop\PlantUML\plantuml_beta.jar
 ortho: False
 


